# Used to generate data for "The labour and resource use requirements of a good life for all"
# Authors: Chris McElroy and Daniel W. O'Neill

categories = [
	'Groceries (food and drinks)',
	'Clothing',
	'Housing',
	'Utilities and insurance',
	'Healthcare',
	'Appliances, furnishing, and maintenance',
	'Education',
	'Devices (computers, phones, TVs)',
	'Transport',
	'Public administration and defense',
	'Recreation (vacations, toys, dining out)',
	'Care work (babysitters, senior care)',
	'Gross fixed capital formation',
	'Not included',
]

decent_living_spending = {
	'Groceries (food and drinks)': 116791.1005457,
	'Clothing': 38979.3571091,
	'Housing': 153052.2860118,
	'Utilities and insurance': 41949.8511241,
	'Healthcare': 35270.4159240,
	'Appliances, furnishing, and maintenance': 0.0000000,
	'Education': 76259.8814877,
	'Devices (computers, phones, TVs)': 11384.0870302,
	'Transport': 101951.0337025,
	'Public administration and defense': 47883.8306440,
	'Recreation (vacations, toys, dining out)': 0.0000000,
	'Care work (babysitters, senior care)': 0.0000000,
	'Gross fixed capital formation': 0.0000000,
	'Not included': 0.0000000,
}

good_life_spending = {
	'Groceries (food and drinks)': 132025.2935291,
	'Clothing': 38979.3571091,
	'Housing': 190546.7626508,
	'Utilities and insurance': 44851.7448485,
	'Healthcare': 191971.1859683,
	'Appliances, furnishing, and maintenance': 32949.1952889,
	'Education': 139680.2683607,
	'Devices (computers, phones, TVs)': 27158.6560661,
	'Transport': 101951.0337025,
	'Public administration and defense': 149197.3391433,
	'Recreation (vacations, toys, dining out)': 124416.4252110,
	'Care work (babysitters, senior care)': 36146.8582766,
	'Gross fixed capital formation': 385352.6773143,
	'Not included': 0.0000000,
}

sector_alignment = {
    'Groceries (food and drinks)': [
		'Paddy rice',
		'Wheat',
		'Cereal grains nec',
		'Vegetables, fruit, nuts',
		'Oil seeds',
		'Sugar cane, sugar beet',
		'Plant-based fibers',
		'Crops nec',
		'Cattle',
		'Pigs',
		'Poultry',
		'Meat animals nec',
		'Animal products nec',
		'Raw milk',
		'Fish and other fishing products; services incidental of fishing (05)',
		'Products of meat cattle',
		'Products of meat pigs',
		'Products of meat poultry',
		'Meat products nec',
		'products of Vegetable oils and fats',
		'Dairy products',
		'Processed rice',
		'Sugar',
		'Food products nec',
		'Beverages',
		'Fish products',
	],
	'Clothing': [
		'Textiles (17)',
		'Wearing apparel; furs (18)',
		'Leather and leather products (19)',
	],
	'Housing': [
		'Real estate services (70)',
	],
	'Utilities and insurance': [
		'Kerosene',
		'Liquefied Petroleum Gases (LPG)',
		'Electricity by coal',
		'Electricity by gas',
		'Electricity by nuclear',
		'Electricity by hydro',
		'Electricity by wind',
		'Electricity by petroleum and other oil derivatives',
		'Electricity by biomass and waste',
		'Electricity by solar photovoltaic',
		'Electricity by solar thermal',
		'Electricity by tide, wave, ocean',
		'Electricity by Geothermal',
		'Electricity nec',
		'Transmission services of electricity',
		'Distribution and trade services of electricity',
		'Natural gas and services related to natural gas extraction, excluding surveying',
		'Other Liquid Biofuels',
		'Coke oven gas',
		'Blast Furnace Gas',
		'Oxygen Steel Furnace Gas',
		'Gas Works Gas',
		'Biogas',
		'Distribution services of gaseous fuels through mains',
		'Steam and hot water supply services',
		'Collected and purified water, distribution services of water (41)',
		'Insurance and pension funding services, except compulsory social security services (66)',
		'Food waste for treatment: incineration',
		'Paper waste for treatment: incineration',
		'Plastic waste for treatment: incineration',
		'Intert/metal waste for treatment: incineration',
		'Textiles waste for treatment: incineration',
		'Wood waste for treatment: incineration',
		'Oil/hazardous waste for treatment: incineration',
		'Food waste for treatment: biogasification and land application',
		'Paper waste for treatment: biogasification and land application',
		'Sewage sludge for treatment: biogasification and land application',
		'Food waste for treatment: composting and land application',
		'Paper and wood waste for treatment: composting and land application',
		'Food waste for treatment: waste water treatment',
		'Other waste for treatment: waste water treatment',
		'Food waste for treatment: landfill',
		'Paper for treatment: landfill',
		'Plastic waste for treatment: landfill',
		'Inert/metal/hazardous waste for treatment: landfill',
		'Textiles waste for treatment: landfill',
		'Wood waste for treatment: landfill',
	],
	'Healthcare': [
		'Health and social work services (85)'
	],
	'Appliances, furnishing, and maintenance': [
		'Electrical machinery and apparatus n.e.c. (31)',
		'Furniture; other manufactured goods n.e.c. (36)',
		'Construction work (45)',
		'Other business services (74)',
		'Retail  trade services, except of motor vehicles and motorcycles; repair services of personal and household goods (52)',
	],
	'Education': [
		'Education services (80)'
	],
	'Devices (computers, phones, TVs)': [
		'Office machinery and computers (30)',
		'Radio, television and communication equipment and apparatus (32)',
		'Post and telecommunication services (64)',
		'Computer and related services (72)',
		'Medical, precision and optical instruments, watches and clocks (33)',
	],
	'Transport': [
		'Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries',
		'Retail trade services of motor fuel',
		'Railway transportation services',
		'Other land transportation services',
		'Transportation services via pipelines',
		'Sea and coastal water transportation services',
		'Inland water transportation services',
		'Air transport services (62)',
		'Supporting and auxiliary transport services; travel agency services (63)',
		'Motor Gasoline',
		'Aviation Gasoline',
		'Gasoline Type Jet Fuel',
		'Kerosene Type Jet Fuel',
		'Gas/Diesel Oil',
		'Biogasoline',
		'Biodiesels',
		'Motor vehicles, trailers and semi-trailers (34)',
		'Other transport equipment (35)',
	],
	'Public administration and defense': [
		'Public administration and defence services; compulsory social security services (75)'
	],
	'Recreation (vacations, toys, dining out)': [
		'Products of forestry, logging and related services (02)',
		'Plastics, basic',
		'Other Bituminous Coal',
		'Sub-Bituminous Coal',
		'Patent Fuel',
		'Lignite/Brown Coal',
		'BKB/Peat Briquettes',
		'Peat',
		'Chemical and fertilizer minerals, salt and other mining and quarrying products n.e.c.',
		'Tobacco products (16)',
		'Wood and products of wood and cork (except furniture); articles of straw and plaiting materials (20)',
		'Paper and paper products',
		'Printed matter and recorded media (22)',
		'Coke Oven Coke',
		'Charcoal',
		'Additives/Blending Components',
		'N-fertiliser',
		'P- and other fertiliser',
		'Chemicals nec',
		'Rubber and plastic products (25)',
		'Ceramic goods',
		'Bricks, tiles and construction products, in baked clay',
		'Cement, lime and plaster',
		'Other non-metallic mineral products',
		'Basic iron and steel and of ferro-alloys and first products thereof',
		'Precious metals',
		'Aluminium and aluminium products',
		'Other non-ferrous metal products',
		'Foundry work services',
		'Fabricated metal products, except machinery and equipment (28)',
		'Machinery and equipment n.e.c. (29)',
		'Secondary raw materials',
		'Wholesale trade and commission trade services, except of motor vehicles and motorcycles (51)',
		'Hotel and restaurant services (55)',
		'Financial intermediation services, except insurance and pension funding services (65)',
		'Services auxiliary to financial intermediation (67)',
		'Renting services of machinery and equipment without operator and of personal and household goods (71)',
		'Research and development services (73)',
		'Membership organisation services n.e.c. (91)',
		'Recreational, cultural and sporting services (92)',
	],
	'Care work (babysitters, senior care)': [
		'Other services (93)',
		'Private households with employed persons (95)',
	],
	'Gross fixed capital formation': [
		# this is handled separately
	],
	'Not included': [
		'Wool, silk-worm cocoons',
		'Manure (conventional treatment)',
		'Manure (biogas treatment)',
		'Anthracite',
		'Coking Coal',
		'Crude petroleum and services related to crude oil extraction, excluding surveying',
		'Natural Gas Liquids',
		'Other Hydrocarbons',
		'Uranium and thorium ores (12)',
		'Iron ores',
		'Copper ores and concentrates',
		'Nickel ores and concentrates',
		'Aluminium ores and concentrates',
		'Precious metal ores and concentrates',
		'Lead, zinc and tin ores and concentrates',
		'Other non-ferrous metal ores and concentrates',
		'Stone',
		'Sand and clay',
		'Wood material for treatment, Re-processing of secondary wood material into new wood material',
		'Pulp',
		'Secondary paper for treatment, Re-processing of secondary paper into new pulp',
		'Gas Coke',
		'Coal Tar',
		'Heavy Fuel Oil',
		'Refinery Gas',
		'Refinery Feedstocks',
		'Ethane',
		'Naphtha',
		'White Spirit & SBP',
		'Lubricants',
		'Bitumen',
		'Paraffin Waxes',
		'Petroleum Coke',
		'Non-specified Petroleum Products',
		'Nuclear fuel',
		'Secondary plastic for treatment, Re-processing of secondary plastic into new plastic',
		'Glass and glass products',
		'Secondary glass for treatment, Re-processing of secondary glass into new glass',
		'Ash for treatment, Re-processing of ash into clinker',
		'Secondary steel for treatment, Re-processing of secondary steel into new steel',
		'Secondary preciuos metals for treatment, Re-processing of secondary preciuos metals into new preciuos metals',
		'Secondary aluminium for treatment, Re-processing of secondary aluminium into new aluminium',
		'Lead, zinc and tin and products thereof',
		'Secondary lead for treatment, Re-processing of secondary lead into new lead',
		'Copper products',
		'Secondary copper for treatment, Re-processing of secondary copper into new copper',
		'Secondary other non-ferrous metals for treatment, Re-processing of secondary other non-ferrous metals into new other non-ferrous metals',
		'Bottles for treatment, Recycling of bottles by direct reuse',
		'Secondary construction material for treatment, Re-processing of secondary construction material into aggregates',
		'Extra-territorial organizations and bodies',
	],
}
